name: dots_indicator_example
description: "Demonstrates how to use the dots_indicator package"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  dots_indicator:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
